[Interface]
Address = 10.0.10.1/24
SaveConfig = true
PostUp = sysctl -w net.ipv4.ip_forward=1; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o enp0s3 -j MASQUERADE
ListenPort = 51820
PrivateKey = uHCggxSthnrjw1W5CNbUFix5wDx512Rne6fF7XBlX2k=

[Peer]
PublicKey = wl5mu0fNe8JdZqyoHfOZQy09Qzw+6thEdgmzjaiRJ0I=

[Peer]
PublicKey = /EyBBjrHjSIOktbZXEFdRQrqEqzGUv4j0LlwZCXGNiE=
AllowedIPs = 10.0.10.2/32
Endpoint = 185.108.19.50:63339

[Peer]
PublicKey = FwbNCe8kuaWFRuVeQ7gPjncf+fPT+b931aV36yjJqi8=
AllowedIPs = 10.0.10.3/32
Endpoint = 185.108.19.50:64028

[Peer]
PublicKey = JFlxM2DXJL5f/0x9rO4X3kB9BrzHRPOtdD5MDwqlH2Q=
AllowedIPs = 10.0.10.4/32

[Peer]
PublicKey = gfWq47KLhg5LridCy2kr/YFQ3xU7dV4Y4q2qthwboWI=
AllowedIPs = 10.0.10.5/32

[Peer]
PublicKey = SkLvcCSLB4thXtuWOUqTEY1tj30rc69z77olnKOb0gw=
AllowedIPs = 10.0.10.6/32

[Peer]
PublicKey = ccr5U1wKqQlVOScwBkiI85F2ABG35giIXDV7Z8MMXy8=
AllowedIPs = 10.0.10.20/32
