[Interface]
PrivateKey = eHe8kCASANcwyGlTpBalOhEwbqsvacNrpBYU9Nv1/Hg=
Address = 10.0.10.4/32
DNS = 1.1.1.1, 1.0.0.1
MTU = 1420

[Peer]
PublicKey = +kHjXeMWLJFg7ipzYeOvadmD7tNyb+PU7h4SMG3RwS8=
Endpoint = 89.22.225.136:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
