def run_content(query):
    q = query.replace("[CONTENT]", "").strip()

    lines = []
    lines.append("КОНТЕНТ-ПАКЕТ")
    lines.append("")
    lines.append("Тема:")
    lines.append(q)
    lines.append("")
    lines.append("Заголовок:")
    lines.append(q)
    lines.append("")
    lines.append("Короткий пост:")
    lines.append("Короткий экспертный пост по теме: " + q)
    lines.append("")
    lines.append("Длинный пост:")
    lines.append("Развёрнутый экспертный пост по теме: " + q + ". Здесь должен быть основной смысл, позиция эксперта и практическая польза")
    lines.append("")
    lines.append("ТЗ на фото:")
    lines.append("— общий план объекта")
    lines.append("— детали узлов")
    lines.append("— проблемные места")
    lines.append("")
    lines.append("ТЗ на видео:")
    lines.append("— вступление")
    lines.append("— показ объекта")
    lines.append("— ключевая мысль")
    lines.append("— вывод")
    return "\n".join(lines)
