def run_content(query):
    q = query.replace("[CONTENT]", "").strip()

    lines = []
    lines.append("КОНТЕНТ-ПАКЕТ")
    lines.append("")
    lines.append("Задача:")
    lines.append(q)
    lines.append("")
    lines.append("Заголовок:")
    lines.append(q)
    lines.append("")
    lines.append("Короткая версия:")
    lines.append("Экспертный пост по теме: " + q)
    lines.append("")
    lines.append("Длинная версия:")
    lines.append("Развёрнутый экспертный материал по теме: " + q)
    lines.append("")
    lines.append("ТЗ на фото/видео:")
    lines.append("— снять общий план")
    lines.append("— снять детали")
    lines.append("— показать процесс")
    lines.append("— добавить подписи и акценты")
    return "\n".join(lines)
